### ISSUE TITLE
can't manually create trustlines

### ISSUE THREAD

**Issue by nielzzz** [stellarterm/stellarterm.github.io#1]
button under section "Manually add tust" -> "Create trust line for XYZ" doesn't do anything.

Reproducable when logged in on: https://stellarterm.com/#account/addTrust

Tested with Jed's HUG (issuer GD5T6IPRNCKFOHQWT264YPKOZAWUMMZOLZBJ6BNQMUGPWGRLBK3U7ZNP)

**Comment by irisli** [comment]
Hi. I put the issue in the correct location. Thanks for opening issue. :)
